#!/usr/bin/env bash
# PreToolUse hook (Edit|Write): refuses edits to generated files and to files
# that hold secrets. Exit 2 blocks the tool call and the stderr text is shown
# to Claude, so the message says what to do instead.
#
# Test: echo '{"tool_input":{"file_path":"/repo/internal/server/api/server.gen.go"}}' | .claude/hooks/protect-paths.sh; echo $?
set -euo pipefail

input=$(cat)
root="${CLAUDE_PROJECT_DIR:-$PWD}"

# Reads a string field of the hook input ($1 is a jq path).
hook_field() {
  if command -v jq >/dev/null 2>&1; then
    jq -r "$1 // empty" <<<"$input"
  elif command -v python3 >/dev/null 2>&1; then
    python3 -I -c '
import json, sys
value = json.load(sys.stdin)
for key in sys.argv[1].strip(".").split("."):
    value = value.get(key, "") if isinstance(value, dict) else ""
print(value if isinstance(value, str) else "")' "$1" <<<"$input"
  else
    echo "protect-paths: neither jq nor python3 found; skipping the check" >&2
  fi
}

file=$(hook_field .tool_input.file_path)
[ -n "$file" ] || exit 0

# Path relative to the project root, for matching and messages.
rel="${file#"$root"/}"

block() {
  printf 'Blocked: %s is %s\n' "$rel" "$1" >&2
  exit 2
}

case "$rel" in
  *.gen.go)
    block "generated by oapi-codegen from api/openapi.yaml. Change the spec and run \`make api-generate\` (ADR-0005)." ;;
  frontend/src/lib/api.gen.ts)
    block "generated by openapi-typescript from api/openapi.yaml. Change the spec and run \`make api-generate\` (ADR-0005)." ;;
  */routeTree.gen.ts|routeTree.gen.ts)
    block "generated by TanStack Router from frontend/src/routes/ and gitignored. Run \`cd frontend && bun run routes:generate\` (also part of \`bun run build\`)." ;;
esac

case "$rel" in
  .env|.env.*|*/.env|*/.env.*|*.local.yaml|*.local.yml|*.pem|*.key|.local/*|deploy/local/*)
    block "a secret file. Credentials never enter the repository or the agent context (AGENTS.md, Security)." ;;
esac

exit 0
