// Copyright 2026 The kafkito Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

// Package frontend embeds the built SPA assets and exposes them as an http.Handler.
//
// The assets are generated by `bun run build` into ./dist. A placeholder index.html
// is checked in so that `go build` works before the frontend has been built; the
// placeholder is overwritten by real assets during `make build`.
package frontend

import (
	"embed"
	"errors"
	"io/fs"
	"net/http"
	"path"
	"strings"
)

//go:embed all:dist
var embedded embed.FS

// Assets returns the built SPA filesystem rooted at dist/.
func Assets() (fs.FS, error) {
	sub, err := fs.Sub(embedded, "dist")
	if err != nil {
		return nil, err
	}
	return sub, nil
}

// Handler returns an http.Handler that serves the embedded SPA with
// index.html fallback for unknown paths (client-side routing).
//
// Paths under /api/ are NOT handled here — mount this handler on everything
// else and let the API routes win via Chi's route ordering.
func Handler() (http.Handler, error) {
	assets, err := Assets()
	if err != nil {
		return nil, err
	}
	fileServer := http.FileServer(http.FS(assets))

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		upath := r.URL.Path
		if upath == "" || upath == "/" {
			serveIndex(w, r, assets)
			return
		}

		cleaned := strings.TrimPrefix(path.Clean(upath), "/")
		if cleaned == "" {
			serveIndex(w, r, assets)
			return
		}

		f, err := assets.Open(cleaned)
		if err != nil {
			if errors.Is(err, fs.ErrNotExist) {
				// Missing files under /assets/ must NOT fall through to
				// index.html — browsers strict-MIME-check hashed bundles and
				// would reject the HTML response. Return a real 404 so the
				// caller (and devtools) sees the failure clearly.
				if strings.HasPrefix(cleaned, "assets/") {
					http.NotFound(w, r)
					return
				}
				serveIndex(w, r, assets)
				return
			}
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		info, statErr := f.Stat()
		_ = f.Close()
		if statErr != nil || info.IsDir() {
			serveIndex(w, r, assets)
			return
		}

		if strings.HasPrefix(cleaned, "assets/") {
			w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		}
		fileServer.ServeHTTP(w, r)
	}), nil
}

func serveIndex(w http.ResponseWriter, r *http.Request, assets fs.FS) {
	data, err := fs.ReadFile(assets, "index.html")
	if err != nil {
		http.Error(w, "index.html not found in embedded assets", http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-cache")
	_, _ = w.Write(data)
	_ = r // keep signature
}
