// Copyright 2026 The kafkito Authors.
// Licensed under the Apache License, Version 2.0.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: kafkito/v1/info.proto

package kafkitov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/FinkeFlo/kafkito/pkg/proto/kafkito/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InfoServiceName is the fully-qualified name of the InfoService service.
	InfoServiceName = "kafkito.v1.InfoService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InfoServiceGetInfoProcedure is the fully-qualified name of the InfoService's GetInfo RPC.
	InfoServiceGetInfoProcedure = "/kafkito.v1.InfoService/GetInfo"
)

// InfoServiceClient is a client for the kafkito.v1.InfoService service.
type InfoServiceClient interface {
	GetInfo(context.Context, *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error)
}

// NewInfoServiceClient constructs a client for the kafkito.v1.InfoService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInfoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InfoServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	infoServiceMethods := v1.File_kafkito_v1_info_proto.Services().ByName("InfoService").Methods()
	return &infoServiceClient{
		getInfo: connect.NewClient[v1.GetInfoRequest, v1.GetInfoResponse](
			httpClient,
			baseURL+InfoServiceGetInfoProcedure,
			connect.WithSchema(infoServiceMethods.ByName("GetInfo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// infoServiceClient implements InfoServiceClient.
type infoServiceClient struct {
	getInfo *connect.Client[v1.GetInfoRequest, v1.GetInfoResponse]
}

// GetInfo calls kafkito.v1.InfoService.GetInfo.
func (c *infoServiceClient) GetInfo(ctx context.Context, req *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error) {
	return c.getInfo.CallUnary(ctx, req)
}

// InfoServiceHandler is an implementation of the kafkito.v1.InfoService service.
type InfoServiceHandler interface {
	GetInfo(context.Context, *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error)
}

// NewInfoServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInfoServiceHandler(svc InfoServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	infoServiceMethods := v1.File_kafkito_v1_info_proto.Services().ByName("InfoService").Methods()
	infoServiceGetInfoHandler := connect.NewUnaryHandler(
		InfoServiceGetInfoProcedure,
		svc.GetInfo,
		connect.WithSchema(infoServiceMethods.ByName("GetInfo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/kafkito.v1.InfoService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InfoServiceGetInfoProcedure:
			infoServiceGetInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInfoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInfoServiceHandler struct{}

func (UnimplementedInfoServiceHandler) GetInfo(context.Context, *connect.Request[v1.GetInfoRequest]) (*connect.Response[v1.GetInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kafkito.v1.InfoService.GetInfo is not implemented"))
}
