// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"

	"github.com/FinkeFlo/kafkito/internal/config"
	"github.com/FinkeFlo/kafkito/internal/kafka"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusOk HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessResponseStatus.
const (
	ReadinessResponseStatusDegraded ReadinessResponseStatus = "degraded"
	ReadinessResponseStatusOk       ReadinessResponseStatus = "ok"
	ReadinessResponseStatusReady    ReadinessResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadinessResponseStatus enum.
func (e ReadinessResponseStatus) Valid() bool {
	switch e {
	case ReadinessResponseStatusDegraded:
		return true
	case ReadinessResponseStatusOk:
		return true
	case ReadinessResponseStatusReady:
		return true
	default:
		return false
	}
}

// BrokerInfo defines model for BrokerInfo.
type BrokerInfo = kafka.BrokerInfo

// Capabilities defines model for Capabilities.
type Capabilities = kafka.Capabilities

// CapabilitiesResponse defines model for CapabilitiesResponse.
type CapabilitiesResponse struct {
	Capabilities Capabilities `json:"capabilities"`
	Cluster      string       `json:"cluster"`
}

// ClusterConfig Ad-hoc ("private") cluster definition supplied per request instead of from the server config — the same JSON the `X-Kafkito-Cluster` header carries (base64-encoded there). Broker and Schema Registry hosts are subject to the server's outbound-host (SSRF) policy.
type ClusterConfig = config.ClusterConfig

// ClusterInfo defines model for ClusterInfo.
type ClusterInfo = kafka.ClusterInfo

// Error Error body emitted by all JSON error paths.
type Error struct {
	// Action RBAC-denied action (403 only).
	Action *string `json:"action,omitempty"`

	// Code Machine-readable code where one exists, e.g. `kafka_upstream`, `production_confirmation_required`, `copy_concurrency_limit`, `kafka_message_too_large`, `kafka_not_authorized`, `rbac_denied`, `topic_consumers_timeout`, `invalid_request` (the request does not match this document; `error` names the parameter or body field and the violated rule, never the submitted value).
	Code *string `json:"code,omitempty"`

	// Error Human-readable message (`unauthorized`, `forbidden`, `not found`, ...).
	Error string `json:"error"`

	// Message Detail for 401 responses from the auth middleware.
	Message *string `json:"message,omitempty"`

	// Resource RBAC-denied resource as `<type>:<name>` (403 only).
	Resource *string `json:"resource,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// InfoResponse defines model for InfoResponse.
type InfoResponse struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// ListBrokersResponse defines model for ListBrokersResponse.
type ListBrokersResponse struct {
	Brokers []BrokerInfo `json:"brokers"`
	Cluster string       `json:"cluster"`
}

// ListClustersResponse defines model for ListClustersResponse.
type ListClustersResponse struct {
	Clusters []ClusterInfo `json:"clusters"`
}

// MaskingRule defines model for MaskingRule.
type MaskingRule struct {
	// Fields JSONPath expressions whose values are replaced.
	Fields *[]string `json:"fields,omitempty"`
	Regex  *[]struct {
		Match       *string `json:"match,omitempty"`
		Replacement *string `json:"replacement,omitempty"`
	} `json:"regex,omitempty"`

	// Replacement Replacement for `fields`; empty = "***".
	Replacement *string   `json:"replacement,omitempty"`
	Topics      *[]string `json:"topics,omitempty"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Anonymous bool   `json:"anonymous"`
	Email     string `json:"email"`

	// Jwt True when a validated principal is present.
	Jwt bool `json:"jwt"`

	// Permissions Map of resource type (or `*`) to allowed actions.
	Permissions map[string][]string `json:"permissions"`
	RbacEnabled bool                `json:"rbac_enabled"`
	Roles       *[]string           `json:"roles"`
	Scopes      *[]string           `json:"scopes"`
	Tenant      string              `json:"tenant"`

	// User Resolved RBAC subject; empty when anonymous.
	User string `json:"user"`
}

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Clusters []ClusterInfo `json:"clusters"`

	// Note Set when no clusters are configured.
	Note   *string                 `json:"note,omitempty"`
	Status ReadinessResponseStatus `json:"status"`
}

// ReadinessResponseStatus defines model for ReadinessResponse.Status.
type ReadinessResponseStatus string

// Cluster defines model for Cluster.
type Cluster = string

// Group defines model for Group.
type Group = string

// PrivateClusterHeader defines model for PrivateClusterHeader.
type PrivateClusterHeader = string

// Subject defines model for Subject.
type Subject = string

// Topic defines model for Topic.
type Topic = string

// BadGateway Error body emitted by all JSON error paths.
type BadGateway = Error

// BadRequest Error body emitted by all JSON error paths.
type BadRequest = Error

// Forbidden Error body emitted by all JSON error paths.
type Forbidden = Error

// NotFound Error body emitted by all JSON error paths.
type NotFound = Error

// Unauthorized Error body emitted by all JSON error paths.
type Unauthorized = Error

// TestClusterParams defines parameters for TestCluster.
type TestClusterParams struct {
	// XKafkitoCluster Base64-encoded JSON `ClusterConfig` of a private (browser-stored) cluster, max 8 KiB decoded. Honoured when the `{cluster}` path segment is `__private__` (required then). RBAC is bypassed for private clusters. A malformed header is rejected with 400.
	XKafkitoCluster *PrivateClusterHeader `json:"X-Kafkito-Cluster,omitempty"`
}

// ListBrokersParams defines parameters for ListBrokers.
type ListBrokersParams struct {
	// XKafkitoCluster Base64-encoded JSON `ClusterConfig` of a private (browser-stored) cluster, max 8 KiB decoded. Honoured when the `{cluster}` path segment is `__private__` (required then). RBAC is bypassed for private clusters. A malformed header is rejected with 400.
	XKafkitoCluster *PrivateClusterHeader `json:"X-Kafkito-Cluster,omitempty"`
}

// GetCapabilitiesParams defines parameters for GetCapabilities.
type GetCapabilitiesParams struct {
	// XKafkitoCluster Base64-encoded JSON `ClusterConfig` of a private (browser-stored) cluster, max 8 KiB decoded. Honoured when the `{cluster}` path segment is `__private__` (required then). RBAC is bypassed for private clusters. A malformed header is rejected with 400.
	XKafkitoCluster *PrivateClusterHeader `json:"X-Kafkito-Cluster,omitempty"`
}

// RefreshCapabilitiesParams defines parameters for RefreshCapabilities.
type RefreshCapabilitiesParams struct {
	// XKafkitoCluster Base64-encoded JSON `ClusterConfig` of a private (browser-stored) cluster, max 8 KiB decoded. Honoured when the `{cluster}` path segment is `__private__` (required then). RBAC is bypassed for private clusters. A malformed header is rejected with 400.
	XKafkitoCluster *PrivateClusterHeader `json:"X-Kafkito-Cluster,omitempty"`
}

// TestClusterJSONRequestBody defines body for TestCluster for application/json ContentType.
type TestClusterJSONRequestBody = ClusterConfig

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListClusters List configured clusters with reachability, capabilities and metrics.
	// (GET /api/v1/clusters)
	ListClusters(w http.ResponseWriter, r *http.Request)
	// TestCluster Probe an ad-hoc cluster definition without storing it.
	// (POST /api/v1/clusters/_test)
	TestCluster(w http.ResponseWriter, r *http.Request, params TestClusterParams)
	// ListBrokers List the brokers of a cluster.
	// (GET /api/v1/clusters/{cluster}/brokers)
	ListBrokers(w http.ResponseWriter, r *http.Request, cluster Cluster, params ListBrokersParams)
	// GetCapabilities Cached capabilities (permissions probed against the broker).
	// (GET /api/v1/clusters/{cluster}/capabilities)
	GetCapabilities(w http.ResponseWriter, r *http.Request, cluster Cluster, params GetCapabilitiesParams)
	// RefreshCapabilities Re-probe capabilities (clears the cache).
	// (POST /api/v1/clusters/{cluster}/capabilities/refresh)
	RefreshCapabilities(w http.ResponseWriter, r *http.Request, cluster Cluster, params RefreshCapabilitiesParams)
	// GetInfo Build info.
	// (GET /api/v1/info)
	GetInfo(w http.ResponseWriter, r *http.Request)
	// GetMe Resolved caller identity and effective permissions.
	// (GET /api/v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// GetOpenApiSpec This OpenAPI document.
	// (GET /api/v1/openapi.yaml)
	GetOpenApiSpec(w http.ResponseWriter, r *http.Request)
	// GetHealth Liveness probe.
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetReadiness Readiness probe. 503 if any configured cluster is unreachable.
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListClusters List configured clusters with reachability, capabilities and metrics.
// (GET /api/v1/clusters)
func (_ Unimplemented) ListClusters(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// TestCluster Probe an ad-hoc cluster definition without storing it.
// (POST /api/v1/clusters/_test)
func (_ Unimplemented) TestCluster(w http.ResponseWriter, r *http.Request, params TestClusterParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListBrokers List the brokers of a cluster.
// (GET /api/v1/clusters/{cluster}/brokers)
func (_ Unimplemented) ListBrokers(w http.ResponseWriter, r *http.Request, cluster Cluster, params ListBrokersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetCapabilities Cached capabilities (permissions probed against the broker).
// (GET /api/v1/clusters/{cluster}/capabilities)
func (_ Unimplemented) GetCapabilities(w http.ResponseWriter, r *http.Request, cluster Cluster, params GetCapabilitiesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RefreshCapabilities Re-probe capabilities (clears the cache).
// (POST /api/v1/clusters/{cluster}/capabilities/refresh)
func (_ Unimplemented) RefreshCapabilities(w http.ResponseWriter, r *http.Request, cluster Cluster, params RefreshCapabilitiesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetInfo Build info.
// (GET /api/v1/info)
func (_ Unimplemented) GetInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe Resolved caller identity and effective permissions.
// (GET /api/v1/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetOpenApiSpec This OpenAPI document.
// (GET /api/v1/openapi.yaml)
func (_ Unimplemented) GetOpenApiSpec(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealth Liveness probe.
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReadiness Readiness probe. 503 if any configured cluster is unreachable.
// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusters(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestCluster operation middleware
func (siw *ServerInterfaceWrapper) TestCluster(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params TestClusterParams

	headers := r.Header

	// ------------- Optional header parameter "X-Kafkito-Cluster" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Kafkito-Cluster")]; found {
		var XKafkitoCluster PrivateClusterHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Kafkito-Cluster", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Kafkito-Cluster", valueList[0], &XKafkitoCluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Kafkito-Cluster", Err: err})
			return
		}

		params.XKafkitoCluster = &XKafkitoCluster

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestCluster(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBrokers operation middleware
func (siw *ServerInterfaceWrapper) ListBrokers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "cluster" -------------
	var cluster Cluster

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", chi.URLParam(r, "cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBrokersParams

	headers := r.Header

	// ------------- Optional header parameter "X-Kafkito-Cluster" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Kafkito-Cluster")]; found {
		var XKafkitoCluster PrivateClusterHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Kafkito-Cluster", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Kafkito-Cluster", valueList[0], &XKafkitoCluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Kafkito-Cluster", Err: err})
			return
		}

		params.XKafkitoCluster = &XKafkitoCluster

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBrokers(w, r, cluster, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCapabilities(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "cluster" -------------
	var cluster Cluster

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", chi.URLParam(r, "cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCapabilitiesParams

	headers := r.Header

	// ------------- Optional header parameter "X-Kafkito-Cluster" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Kafkito-Cluster")]; found {
		var XKafkitoCluster PrivateClusterHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Kafkito-Cluster", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Kafkito-Cluster", valueList[0], &XKafkitoCluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Kafkito-Cluster", Err: err})
			return
		}

		params.XKafkitoCluster = &XKafkitoCluster

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCapabilities(w, r, cluster, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshCapabilities operation middleware
func (siw *ServerInterfaceWrapper) RefreshCapabilities(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "cluster" -------------
	var cluster Cluster

	err = runtime.BindStyledParameterWithOptions("simple", "cluster", chi.URLParam(r, "cluster"), &cluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshCapabilitiesParams

	headers := r.Header

	// ------------- Optional header parameter "X-Kafkito-Cluster" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Kafkito-Cluster")]; found {
		var XKafkitoCluster PrivateClusterHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Kafkito-Cluster", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Kafkito-Cluster", valueList[0], &XKafkitoCluster, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Kafkito-Cluster", Err: err})
			return
		}

		params.XKafkitoCluster = &XKafkitoCluster

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshCapabilities(w, r, cluster, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInfo operation middleware
func (siw *ServerInterfaceWrapper) GetInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpenApiSpec operation middleware
func (siw *ServerInterfaceWrapper) GetOpenApiSpec(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenApiSpec(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/clusters", wrapper.ListClusters)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/clusters/_test", wrapper.TestCluster)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/clusters/{cluster}/brokers", wrapper.ListBrokers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/clusters/{cluster}/capabilities", wrapper.GetCapabilities)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/clusters/{cluster}/capabilities/refresh", wrapper.RefreshCapabilities)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/info", wrapper.GetInfo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/openapi.yaml", wrapper.GetOpenApiSpec)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})

	return r
}

type BadGatewayJSONResponse Error

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedResponseHeaders struct {
	WWWAuthenticate *string
}
type UnauthorizedJSONResponse struct {
	Body Error

	Headers UnauthorizedResponseHeaders
}

type ListClustersRequestObject struct {
}

type ListClustersResponseObject interface {
	VisitListClustersResponse(w http.ResponseWriter) error
}

type ListClusters200JSONResponse ListClustersResponse

func (response ListClusters200JSONResponse) VisitListClustersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListClusters401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListClusters401JSONResponse) VisitListClustersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type TestClusterRequestObject struct {
	Params TestClusterParams
	Body   *TestClusterJSONRequestBody
}

type TestClusterResponseObject interface {
	VisitTestClusterResponse(w http.ResponseWriter) error
}

type TestCluster200JSONResponse ClusterInfo

func (response TestCluster200JSONResponse) VisitTestClusterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type TestCluster400JSONResponse struct{ BadRequestJSONResponse }

func (response TestCluster400JSONResponse) VisitTestClusterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type TestCluster401JSONResponse struct{ UnauthorizedJSONResponse }

func (response TestCluster401JSONResponse) VisitTestClusterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListBrokersRequestObject struct {
	Cluster Cluster `json:"cluster"`
	Params  ListBrokersParams
}

type ListBrokersResponseObject interface {
	VisitListBrokersResponse(w http.ResponseWriter) error
}

type ListBrokers200JSONResponse ListBrokersResponse

func (response ListBrokers200JSONResponse) VisitListBrokersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListBrokers400JSONResponse struct{ BadRequestJSONResponse }

func (response ListBrokers400JSONResponse) VisitListBrokersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListBrokers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListBrokers401JSONResponse) VisitListBrokersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListBrokers403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListBrokers403JSONResponse) VisitListBrokersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListBrokers404JSONResponse struct{ NotFoundJSONResponse }

func (response ListBrokers404JSONResponse) VisitListBrokersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListBrokers502JSONResponse struct{ BadGatewayJSONResponse }

func (response ListBrokers502JSONResponse) VisitListBrokersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetCapabilitiesRequestObject struct {
	Cluster Cluster `json:"cluster"`
	Params  GetCapabilitiesParams
}

type GetCapabilitiesResponseObject interface {
	VisitGetCapabilitiesResponse(w http.ResponseWriter) error
}

type GetCapabilities200JSONResponse CapabilitiesResponse

func (response GetCapabilities200JSONResponse) VisitGetCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCapabilities400JSONResponse struct{ BadRequestJSONResponse }

func (response GetCapabilities400JSONResponse) VisitGetCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetCapabilities401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCapabilities401JSONResponse) VisitGetCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetCapabilities404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCapabilities404JSONResponse) VisitGetCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetCapabilities502JSONResponse struct{ BadGatewayJSONResponse }

func (response GetCapabilities502JSONResponse) VisitGetCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshCapabilitiesRequestObject struct {
	Cluster Cluster `json:"cluster"`
	Params  RefreshCapabilitiesParams
}

type RefreshCapabilitiesResponseObject interface {
	VisitRefreshCapabilitiesResponse(w http.ResponseWriter) error
}

type RefreshCapabilities200JSONResponse CapabilitiesResponse

func (response RefreshCapabilities200JSONResponse) VisitRefreshCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshCapabilities400JSONResponse struct{ BadRequestJSONResponse }

func (response RefreshCapabilities400JSONResponse) VisitRefreshCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshCapabilities401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshCapabilities401JSONResponse) VisitRefreshCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshCapabilities404JSONResponse struct{ NotFoundJSONResponse }

func (response RefreshCapabilities404JSONResponse) VisitRefreshCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshCapabilities502JSONResponse struct{ BadGatewayJSONResponse }

func (response RefreshCapabilities502JSONResponse) VisitRefreshCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetInfoRequestObject struct {
}

type GetInfoResponseObject interface {
	VisitGetInfoResponse(w http.ResponseWriter) error
}

type GetInfo200JSONResponse InfoResponse

func (response GetInfo200JSONResponse) VisitGetInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInfo401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetInfo401JSONResponse) VisitGetInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse MeResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOpenApiSpecRequestObject struct {
}

type GetOpenApiSpecResponseObject interface {
	VisitGetOpenApiSpecResponse(w http.ResponseWriter) error
}

type GetOpenApiSpec200ApplicationyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetOpenApiSpec200ApplicationyamlResponse) VisitGetOpenApiSpecResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetOpenApiSpec401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetOpenApiSpec401JSONResponse) VisitGetOpenApiSpecResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse ReadinessResponse

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness503JSONResponse ReadinessResponse

func (response GetReadiness503JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListClusters List configured clusters with reachability, capabilities and metrics.
	// (GET /api/v1/clusters)
	ListClusters(ctx context.Context, request ListClustersRequestObject) (ListClustersResponseObject, error)
	// TestCluster Probe an ad-hoc cluster definition without storing it.
	// (POST /api/v1/clusters/_test)
	TestCluster(ctx context.Context, request TestClusterRequestObject) (TestClusterResponseObject, error)
	// ListBrokers List the brokers of a cluster.
	// (GET /api/v1/clusters/{cluster}/brokers)
	ListBrokers(ctx context.Context, request ListBrokersRequestObject) (ListBrokersResponseObject, error)
	// GetCapabilities Cached capabilities (permissions probed against the broker).
	// (GET /api/v1/clusters/{cluster}/capabilities)
	GetCapabilities(ctx context.Context, request GetCapabilitiesRequestObject) (GetCapabilitiesResponseObject, error)
	// RefreshCapabilities Re-probe capabilities (clears the cache).
	// (POST /api/v1/clusters/{cluster}/capabilities/refresh)
	RefreshCapabilities(ctx context.Context, request RefreshCapabilitiesRequestObject) (RefreshCapabilitiesResponseObject, error)
	// GetInfo Build info.
	// (GET /api/v1/info)
	GetInfo(ctx context.Context, request GetInfoRequestObject) (GetInfoResponseObject, error)
	// GetMe Resolved caller identity and effective permissions.
	// (GET /api/v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// GetOpenApiSpec This OpenAPI document.
	// (GET /api/v1/openapi.yaml)
	GetOpenApiSpec(ctx context.Context, request GetOpenApiSpecRequestObject) (GetOpenApiSpecResponseObject, error)
	// GetHealth Liveness probe.
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// GetReadiness Readiness probe. 503 if any configured cluster is unreachable.
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListClusters operation middleware
func (sh *strictHandler) ListClusters(w http.ResponseWriter, r *http.Request) {
	var request ListClustersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListClusters(ctx, request.(ListClustersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListClusters")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListClustersResponseObject); ok {
		if err := validResponse.VisitListClustersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TestCluster operation middleware
func (sh *strictHandler) TestCluster(w http.ResponseWriter, r *http.Request, params TestClusterParams) {
	var request TestClusterRequestObject

	request.Params = params

	var body TestClusterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TestCluster(ctx, request.(TestClusterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestCluster")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TestClusterResponseObject); ok {
		if err := validResponse.VisitTestClusterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListBrokers operation middleware
func (sh *strictHandler) ListBrokers(w http.ResponseWriter, r *http.Request, cluster Cluster, params ListBrokersParams) {
	var request ListBrokersRequestObject

	request.Cluster = cluster
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBrokers(ctx, request.(ListBrokersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBrokers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBrokersResponseObject); ok {
		if err := validResponse.VisitListBrokersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCapabilities operation middleware
func (sh *strictHandler) GetCapabilities(w http.ResponseWriter, r *http.Request, cluster Cluster, params GetCapabilitiesParams) {
	var request GetCapabilitiesRequestObject

	request.Cluster = cluster
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCapabilities(ctx, request.(GetCapabilitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCapabilities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCapabilitiesResponseObject); ok {
		if err := validResponse.VisitGetCapabilitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshCapabilities operation middleware
func (sh *strictHandler) RefreshCapabilities(w http.ResponseWriter, r *http.Request, cluster Cluster, params RefreshCapabilitiesParams) {
	var request RefreshCapabilitiesRequestObject

	request.Cluster = cluster
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshCapabilities(ctx, request.(RefreshCapabilitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshCapabilities")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshCapabilitiesResponseObject); ok {
		if err := validResponse.VisitRefreshCapabilitiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInfo operation middleware
func (sh *strictHandler) GetInfo(w http.ResponseWriter, r *http.Request) {
	var request GetInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInfo(ctx, request.(GetInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInfoResponseObject); ok {
		if err := validResponse.VisitGetInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOpenApiSpec operation middleware
func (sh *strictHandler) GetOpenApiSpec(w http.ResponseWriter, r *http.Request) {
	var request GetOpenApiSpecRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenApiSpec(ctx, request.(GetOpenApiSpecRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenApiSpec")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOpenApiSpecResponseObject); ok {
		if err := validResponse.VisitGetOpenApiSpecResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
